### ISSUE TITLE
Why not use ES6 classes extending Ember.Component directly?

### ISSUE THREAD

**Issue by jayphelps** [ebryn/ember-es6-component#2]
While you lose the ability to add additional mixins (a decorator could overcome that), in my testing it _appears_ you can actually extend ember's core objects with ES6 classes.

Surely there are things this breaks that I'm missing?

``` js
class ApplicationRoute extends Ember.Route {
  model() {
    return {
      msg: 'ya\'ll'
    };
  }  
}

class HelloWorldComponent extends Ember.Component {
  // ...
}
```

[JSBin Demo](http://emberjs.jsbin.com/ququlu/1/edit?html,js,output)

I even tested `super` functionality and it seemed to work correctly, as well as internals seemed to get setup right (guid, meta, etc).

**Comment by ebryn** [comment]
The renderer was built so we could have components that didn't have to be instances of Ember.Component. I'm more interested in exploring a purely ES6 implementation here than piggybacking the existing parent class.
